services:
  moon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output/moon:/app/output
  spicey:
    build:
      context: ./spicey
      dockerfile: Dockerfile
    volumes:
      - ./output/spicey:/app/output