name: Update Discord PFP with Accurate Moon Phase (Astropy)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-moon-phase:
    runs-on: ubuntu-latest
    outputs:
      moon-phase: ${{ steps.get_moon_phase.outputs.moon_phase }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Get Moon Phase
        id: get_moon_phase
        run: |
          phase=$(python get_phase.py)
          echo "Moon Phase: $phase"
          echo "moon_phase=$phase" >> $GITHUB_OUTPUT
  change-pfp:
    runs-on: ubuntu-latest
    needs: get-moon-phase
#    env:
#      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run js action
        uses: ./.github/actions/change-pfp
        with:
          moon_phase: ${{ needs.get-moon-phase.outputs.moon-phase }}.png
